import { PrismaClient } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"
import dotenv from "dotenv"
import path from "path"

dotenv.config({ path: path.resolve(__dirname, "../.env.local") })

const databaseUrl = process.env.DATABASE_URL
if (!databaseUrl) throw new Error("DATABASE_URL is not set")

const adapter = new PrismaPg(databaseUrl)
const prisma = new PrismaClient({ adapter })

const products = [
  {
    name: "Premium Cotton T-Shirt",
    slug: "premium-cotton-tshirt",
    description: "Ultra-soft 100% organic cotton t-shirt with a relaxed fit. Pre-shrunk fabric ensures lasting comfort.",
    category: "Clothing",
    brand: "Essentials",
    price: 39.99,
    discountPrice: null,
    stock: 150,
    sku: "PCT-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Oversized Linen Shirt",
    slug: "oversized-linen-shirt",
    description: "Breathable linen shirt with an oversized silhouette. Perfect for warm-weather layering.",
    category: "Clothing",
    brand: "Essentials",
    price: 79.99,
    discountPrice: 59.99,
    stock: 75,
    sku: "OLS-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Wool Blend Coat",
    slug: "wool-blend-coat",
    description: "Tailored wool-blend coat with notched lapels and a double-breasted closure.",
    category: "Clothing",
    brand: "Luxury Line",
    price: 299.99,
    discountPrice: null,
    stock: 30,
    sku: "WBC-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Minimalist Leather Bag",
    slug: "minimalist-leather-bag",
    description: "Handcrafted full-grain leather tote with minimalist hardware and a spacious interior.",
    category: "Accessories",
    brand: "Luxury Line",
    price: 249.99,
    discountPrice: 199.99,
    stock: 25,
    sku: "MLB-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Ceramic Mug Set",
    slug: "ceramic-mug-set",
    description: "Set of 4 hand-thrown ceramic mugs with matte glaze. Dishwasher and microwave safe.",
    category: "Home",
    brand: "Artisan",
    price: 44.99,
    discountPrice: null,
    stock: 200,
    sku: "CMS-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Wireless Headphones Pro",
    slug: "wireless-headphones-pro",
    description: "Premium noise-cancelling wireless headphones with 40-hour battery life and hi-res audio.",
    category: "Electronics",
    brand: "TechGear",
    price: 349.99,
    discountPrice: 299.99,
    stock: 60,
    sku: "WHP-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Slim Fit Chinos",
    slug: "slim-fit-chinos",
    description: "Stretch-cotton chinos with a modern slim fit. Wrinkle-resistant fabric for all-day wear.",
    category: "Clothing",
    brand: "Essentials",
    price: 69.99,
    discountPrice: null,
    stock: 120,
    sku: "SFC-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Handmade Wool Scarf",
    slug: "handmade-wool-scarf",
    description: "Artisan-knit merino wool scarf with fringed edges. Available in heather grey.",
    category: "Accessories",
    brand: "Artisan",
    price: 59.99,
    discountPrice: 39.99,
    stock: 40,
    sku: "HWS-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Stainless Steel Water Bottle",
    slug: "stainless-steel-water-bottle",
    description: "Double-walled vacuum insulated bottle. Keeps drinks cold 24h or hot 12h. 750ml capacity.",
    category: "Home",
    brand: "TechGear",
    price: 34.99,
    discountPrice: null,
    stock: 250,
    sku: "SSB-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Leather Chelsea Boots",
    slug: "leather-chelsea-boots",
    description: "Italian leather Chelsea boots with elastic side panels and pull tab. Blake stitched.",
    category: "Footwear",
    brand: "Luxury Line",
    price: 389.99,
    discountPrice: null,
    stock: 20,
    sku: "LCB-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Cashmere Crew Neck Sweater",
    slug: "cashmere-crew-neck-sweater",
    description: "Luxuriously soft cashmere sweater with ribbed cuffs and hem. Lightweight yet warm.",
    category: "Clothing",
    brand: "Luxury Line",
    price: 199.99,
    discountPrice: 149.99,
    stock: 35,
    sku: "CCN-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Scented Soy Candle Set",
    slug: "scented-soy-candle-set",
    description: "Set of 3 hand-poured soy candles. Sandalwood, Vanilla, and Cedar 8oz each.",
    category: "Home",
    brand: "Artisan",
    price: 54.99,
    discountPrice: null,
    stock: 90,
    sku: "SCS-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Ultralight Running Shoes",
    slug: "ultralight-running-shoes",
    description: "Carbon-plate running shoes with responsive foam midsole. 7.2oz weight. Breathable knit upper.",
    category: "Footwear",
    brand: "TechGear",
    price: 179.99,
    discountPrice: 139.99,
    stock: 45,
    sku: "URS-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Canvas Backpack",
    slug: "canvas-backpack",
    description: "Waxed canvas backpack with leather straps and padded laptop sleeve. 25L capacity.",
    category: "Accessories",
    brand: "Essentials",
    price: 129.99,
    discountPrice: null,
    stock: 80,
    sku: "CBP-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Smart Watch Ultra",
    slug: "smart-watch-ultra",
    description: "GPS-enabled smartwatch with AMOLED display, heart rate monitor, and 14-day battery.",
    category: "Electronics",
    brand: "TechGear",
    price: 449.99,
    discountPrice: 399.99,
    stock: 15,
    sku: "SWU-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Denim Jacket",
    slug: "denim-jacket",
    description: "Classic denim jacket in medium wash. Button front with chest pockets and adjustable waist.",
    category: "Clothing",
    brand: "Essentials",
    price: 89.99,
    discountPrice: null,
    stock: 55,
    sku: "DJK-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Bamboo Cutting Board Set",
    slug: "bamboo-cutting-board-set",
    description: "Set of 3 organic bamboo cutting boards in graduated sizes. Knife-friendly and antimicrobial.",
    category: "Home",
    brand: "Artisan",
    price: 39.99,
    discountPrice: null,
    stock: 160,
    sku: "BCS-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Aviator Sunglasses",
    slug: "aviator-sunglasses",
    description: "Gold-frame aviator sunglasses with polarized UV400 lenses. Includes hard case.",
    category: "Accessories",
    brand: "Luxury Line",
    price: 159.99,
    discountPrice: 119.99,
    stock: 65,
    sku: "AVS-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Portable Bluetooth Speaker",
    slug: "portable-bluetooth-speaker",
    description: "Waterproof portable speaker with 360° sound, 20-hour battery, and built-in microphone.",
    category: "Electronics",
    brand: "TechGear",
    price: 79.99,
    discountPrice: null,
    stock: 100,
    sku: "PBS-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Merino Wool Base Layer",
    slug: "merino-wool-base-layer",
    description: "Ultralight merino wool base layer with flatlock seams. Temperature regulating and odor resistant.",
    category: "Clothing",
    brand: "Essentials",
    price: 89.99,
    discountPrice: 69.99,
    stock: 85,
    sku: "MWB-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Leather Belt",
    slug: "leather-belt",
    description: "Full-grain Italian leather belt with brushed nickel buckle. 35mm width. Hand-finished edges.",
    category: "Accessories",
    brand: "Luxury Line",
    price: 89.99,
    discountPrice: null,
    stock: 110,
    sku: "LBT-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "French Press Coffee Maker",
    slug: "french-press-coffee-maker",
    description: "34oz borosilicate glass French press with stainless steel plunger and mesh filter.",
    category: "Home",
    brand: "Artisan",
    price: 49.99,
    discountPrice: 39.99,
    stock: 70,
    sku: "FPC-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Mechanical Keyboard",
    slug: "mechanical-keyboard",
    description: "80% mechanical keyboard with Cherry MX Brown switches. Hot-swappable PCB. Per-key RGB.",
    category: "Electronics",
    brand: "TechGear",
    price: 169.99,
    discountPrice: null,
    stock: 3,
    sku: "MKB-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Linen Summer Dress",
    slug: "linen-summer-dress",
    description: "Flowy linen midi dress with adjustable waist tie and side pockets. Breathable and lightweight.",
    category: "Clothing",
    brand: "Essentials",
    price: 94.99,
    discountPrice: null,
    stock: 40,
    sku: "LSD-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Leather Wallet",
    slug: "leather-wallet",
    description: "Slim bifold wallet crafted from Horween leather. Holds 8 cards plus cash slot.",
    category: "Accessories",
    brand: "Luxury Line",
    price: 69.99,
    discountPrice: null,
    stock: 95,
    sku: "LWL-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Indoor Plant Pot Set",
    slug: "indoor-plant-pot-set",
    description: "Set of 3 matte ceramic plant pots with drainage holes and bamboo trays. 4, 6, 8 inch.",
    category: "Home",
    brand: "Artisan",
    price: 64.99,
    discountPrice: null,
    stock: 50,
    sku: "IPP-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Wireless Charging Pad",
    slug: "wireless-charging-pad",
    description: "15W fast wireless charger compatible with all Qi devices. Slim aluminum design with LED indicator.",
    category: "Electronics",
    brand: "TechGear",
    price: 29.99,
    discountPrice: null,
    stock: 180,
    sku: "WCP-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Hiking Boots",
    slug: "hiking-boots",
    description: "Waterproof leather hiking boots with Vibram sole and cushioned ankle support.",
    category: "Footwear",
    brand: "Essentials",
    price: 219.99,
    discountPrice: 179.99,
    stock: 0,
    sku: "HKB-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Silk Face Mask Set",
    slug: "silk-face-mask-set",
    description: "Set of 2 mulberry silk face masks with adjustable ear loops. Reusable and breathable. Includes silk pouch.",
    category: "Accessories",
    brand: "Luxury Line",
    price: 34.99,
    discountPrice: null,
    stock: 0,
    sku: "SFM-001",
    images: [],
    status: "ACTIVE" as const,
  },
  {
    name: "Cast Iron Skillet",
    slug: "cast-iron-skillet",
    description: "Pre-seasoned 12-inch cast iron skillet with helper handle. Oven safe to 500°F. Heirloom quality.",
    category: "Home",
    brand: "Artisan",
    price: 59.99,
    discountPrice: null,
    stock: 65,
    sku: "CIS-001",
    images: [],
    status: "INACTIVE" as const,
  },
]

async function main() {
  let created = 0
  for (const product of products) {
    const existingSlug = await prisma.product.findUnique({ where: { slug: product.slug } })
    if (existingSlug) {
      console.log(`Skipping ${product.slug} — already exists`)
      continue
    }
    const existingSku = await prisma.product.findUnique({ where: { sku: product.sku } })
    if (existingSku) {
      console.log(`Skipping ${product.sku} — SKU already exists`)
      continue
    }
    await prisma.product.create({ data: product })
    console.log(`Created: ${product.name} (${product.slug})`)
    created++
  }

  for (const product of products) {
    await prisma.productInventory.upsert({
      where: { productId: product.slug },
      update: { stock: product.stock, sku: product.sku },
      create: { productId: product.slug, stock: product.stock, sku: product.sku },
    })
  }

  console.log(`\nDone. Created ${created} new products. Total in DB: ${await prisma.product.count({ where: { deletedAt: null } })}`)
  await prisma.$disconnect()
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
